### PR TITLE
[chunkwriting] Handle data races in chunk IDs

### PR DESCRIPTION
**Pull request by kfarnung**
During test execution `TestCopyFromReader` hit a data race which
resulted in the test failing due to checksum mismatch.

Since the `id` struct's methods are not thread-safe there is a race
condition where two upload threads request an ID at the same moment and
both could potentially end up with the same ID.

The simplest solution is to move the ID assignment to the thread that
populates the chunks to the channel. This ensures that the chunk IDs are
assigned sequentially and removes the race condition.

Introduced by #167

### CODE REVIEW

**Comment by kfarnung** [comment]
I setup Travis CI and this hit during a build. my changes were unrelated to this entire codepath:

https://travis-ci.com/github/kfarnung/azure-storage-blob-go/builds/168138261

```text
=== CONT  TestCopyFromReader
==================
WARNING: DATA RACE
Read at 0x00c0006c7600 by goroutine 12:
  github.com/Azure/azure-kusto-go/azblob.(*id).next()
      /home/travis/gopath/src/github.com/kfarnung/azure-storage-blob-go/azblob/chunkwriting.go:217 +0xce
  github.com/Azure/azure-kusto-go/azblob.(*copier).write()
      /home/travis/gopath/src/github.com/kfarnung/azure-storage-blob-go/azblob/chunkwriting.go:177 +0x177
  github.com/Azure/azure-kusto-go/azblob.(*copier).writer()
      /home/travis/gopath/src/github.com/kfarnung/azure-storage-blob-go/azblob/chunkwriting.go:156 +0x193

Previous write at 0x00c0006c7600 by goroutine 89:
  github.com/Azure/azure-kusto-go/azblob.(*id).next.func1()
      /home/travis/gopath/src/github.com/kfarnung/azure-storage-blob-go/azblob/chunkwriting.go:215 +0x79
  github.com/Azure/azure-kusto-go/azblob.(*id).next()
      /home/travis/gopath/src/github.com/kfarnung/azure-storage-blob-go/azblob/chunkwriting.go:221 +0x2cf
  github.com/Azure/azure-kusto-go/azblob.(*copier).write()
      /home/travis/gopath/src/github.com/kfarnung/azure-storage-blob-go/azblob/chunkwriting.go:177 +0x177
  github.com/Azure/azure-kusto-go/azblob.(*copier).writer()
      /home/travis/gopath/src/github.com/kfarnung/azure-storage-blob-go/azblob/chunkwriting.go:156 +0x193

Goroutine 12 (running) created at:
  github.com/Azure/azure-kusto-go/azblob.copyFromReader()
      /home/travis/gopath/src/github.com/kfarnung/azure-storage-blob-go/azblob/chunkwriting.go:56 +0x565
  github.com/Azure/azure-kusto-go/azblob.TestCopyFromReader()
      /home/travis/gopath/src/github.com/kfarnung/azure-storage-blob-go/azblob/chunkwriting_test.go:254 +0x525
  testing.tRunner()
      /home/travis/.gimme/versions/go1.13.linux.amd64/src/testing/testing.go:909 +0x199

Goroutine 89 (running) created at:
  github.com/Azure/azure-kusto-go/azblob.copyFromReader()
      /home/travis/gopath/src/github.com/kfarnung/azure-storage-blob-go/azblob/chunkwriting.go:56 +0x565
  github.com/Azure/azure-kusto-go/azblob.TestCopyFromReader()
      /home/travis/gopath/src/github.com/kfarnung/azure-storage-blob-go/azblob/chunkwriting_test.go:254 +0x525
  testing.tRunner()
      /home/travis/.gimme/versions/go1.13.linux.amd64/src/testing/testing.go:909 +0x199
==================
==================
WARNING: DATA RACE
Read at 0x00c0006c7608 by goroutine 12:
  github.com/Azure/azure-kusto-go/azblob.(*id).next()
      /home/travis/gopath/src/github.com/kfarnung/azure-storage-blob-go/azblob/chunkwriting.go:219 +0x1ea
  github.com/Azure/azure-kusto-go/azblob.(*copier).write()
      /home/travis/gopath/src/github.com/kfarnung/azure-storage-blob-go/azblob/chunkwriting.go:177 +0x177
  github.com/Azure/azure-kusto-go/azblob.(*copier).writer()
      /home/travis/gopath/src/github.com/kfarnung/azure-storage-blob-go/azblob/chunkwriting.go:156 +0x193

Previous write at 0x00c0006c7608 by goroutine 89:
  github.com/Azure/azure-kusto-go/azblob.(*id).next()
      /home/travis/gopath/src/github.com/kfarnung/azure-storage-blob-go/azblob/chunkwriting.go:219 +0x27f
  github.com/Azure/azure-kusto-go/azblob.(*copier).write()
      /home/travis/gopath/src/github.com/kfarnung/azure-storage-blob-go/azblob/chunkwriting.go:177 +0x177
  github.com/Azure/azure-kusto-go/azblob.(*copier).writer()
      /home/travis/gopath/src/github.com/kfarnung/azure-storage-blob-go/azblob/chunkwriting.go:156 +0x193

Goroutine 12 (running) created at:
  github.com/Azure/azure-kusto-go/azblob.copyFromReader()
      /home/travis/gopath/src/github.com/kfarnung/azure-storage-blob-go/azblob/chunkwriting.go:56 +0x565
  github.com/Azure/azure-kusto-go/azblob.TestCopyFromReader()
      /home/travis/gopath/src/github.com/kfarnung/azure-storage-blob-go/azblob/chunkwriting_test.go:254 +0x525
  testing.tRunner()
      /home/travis/.gimme/versions/go1.13.linux.amd64/src/testing/testing.go:909 +0x199

Goroutine 89 (running) created at:
  github.com/Azure/azure-kusto-go/azblob.copyFromReader()
      /home/travis/gopath/src/github.com/kfarnung/azure-storage-blob-go/azblob/chunkwriting.go:56 +0x565
  github.com/Azure/azure-kusto-go/azblob.TestCopyFromReader()
      /home/travis/gopath/src/github.com/kfarnung/azure-storage-blob-go/azblob/chunkwriting_test.go:254 +0x525
  testing.tRunner()
      /home/travis/.gimme/versions/go1.13.linux.amd64/src/testing/testing.go:909 +0x199
==================
--- FAIL: TestCopyFromReader (2.63s)
    chunkwriting_test.go:270: TestCopyFromReader(Send file(12 MiB) with 3 writers and 1.5 MiB buffer): MD5 not the same: got 880c522a2ad00f2c91e138f23b9fbe64, want 22a298e5bb3e1a617c32d1d26d963ab8
    testing.go:853: race detected during execution of test
```

**Comment by element-of-surprise** [comment]
Hey Kyle,

Thanks for bringing it to my attention.  I'll have a look and see what's going on.  I know I ran the data race detector on my changes, but its a fickle beast with no two runs being the same.

Cheers,

John Doak
Manager, Fleet Process Engineering
jdoak@microsoft.com

What is Fleet Process Engineering? Click here<https://msit.microsoftstream.com/video/324beca9-b636-4ffb-8b5b-fa527b9ee292?list=studio> to find out!
________________________________

**Comment by kfarnung** [comment]
Thanks @element-of-surprise, have a look at my proposed change here. I'm not sure of the evolution of the change, but it looks like the ID management code explicitly says it's not thread-safe, but it's being used from the writer thread. Since there are multiple writer threads it's not possible to guarantee single-threaded access.

I've only seen this failure so far when running the test suite against my unrelated change, so I'm not 100% sure why it's causing this race to be detected when it otherwise is not. That said, I'm pretty confident in the investigation and fix, so feedback would be appreciated.

**Comment by kfarnung** [comment]
CI run: https://travis-ci.com/github/kfarnung/azure-storage-blob-go/builds/168149751

**Comment by kfarnung** [comment]
CI run of this change along with the change that seems to trigger the failure (#175):

https://travis-ci.com/github/kfarnung/azure-storage-blob-go/builds/168238361

**Comment by zezha-msft** [comment]
Thank you @kfarnung for the excellent investigation and solution!

**Comment by zezha-msft** [comment]
I just observed it here too: https://travis-ci.org/github/Azure/azure-storage-blob-go/builds/701479995

**Comment by element-of-surprise** [comment]
Sorry, not that I've been asleep at the wheel, but end of semester stuff keeping me busy.

I'll have a look, because this next() call shouldn't be happening concurrently.  Its an easy fix using atomic, but I want to figure out why that is happening.  At first glance its not obvious, should be doing that in sequence that then causes an upload in parallel.

John Doak
Manager, Fleet Process Engineering
jdoak@microsoft.com

What is Fleet Process Engineering? Click here<https://msit.microsoftstream.com/video/324beca9-b636-4ffb-8b5b-fa527b9ee292?list=studio> to find out!
________________________________

**Comment by kfarnung** [comment]
Here's the flow:

These lines create multiple `writer` goroutines:

https://github.com/Azure/azure-storage-blob-go/blob/3bddf3825abef41370d9ce60e9ba2ec6a1ca9da2/azblob/chunkwriting.go#L55-L57

Each one of those goroutines calls `write`:

https://github.com/Azure/azure-storage-blob-go/blob/3bddf3825abef41370d9ce60e9ba2ec6a1ca9da2/azblob/chunkwriting.go#L155-L157

And `write` calls `next`:

https://github.com/Azure/azure-storage-blob-go/blob/3bddf3825abef41370d9ce60e9ba2ec6a1ca9da2/azblob/chunkwriting.go#L177

Without any synchronization this call chain is inherently racy. Since each thread is independent the first thread could be assigned work and then paused by the OS. During that time a second thread could come in, grab another work item, and the original thread could be resumed. That places them both in a race to get the next ID value.

I considered doing atomic operations, but it seemed cleaner and easier to just avoid the race condition entirely by assigning the `id` values when feeding the work into the channel.

**Comment by zezha-msft** [comment]
Hi @element-of-surprise, I'm going to merge this now, but please do let us know if you have any concern or comment.

**Comment by element-of-surprise** [comment]
The current dev doesn't seem to be showing any race conditions.  I've been running the race tests on it now about 10 times, no races have shown.

Ze, are you still seeing any race conditions?

What is showing up is something that wasn't there before:

----------------------------------------------------------------------
FAIL: zt_url_append_blob_test.go:78: aztestsSuite.TestAppendBlockFromURL

zt_url_append_blob_test.go:132:
    c.Assert(appendFromURLResp.BlobAppendOffset(), chk.Equals, "0")
... obtained string = "18446744073709551615"
... expected string = "0"


----------------------------------------------------------------------
FAIL: zt_url_append_blob_test.go:149: aztestsSuite.TestAppendBlockFromURLWithMD5

zt_url_append_blob_test.go:204:
    c.Assert(appendFromURLResp.BlobAppendOffset(), chk.Equals, "0")
... obtained string = "18446744073709551615"
... expected string = "0"

I assume that is something else that got pushed into dev, but you either have a broken test or broken code.

John Doak
Manager, Fleet Process Engineering
jdoak@microsoft.com

What is Fleet Process Engineering? Click here<https://msit.microsoftstream.com/video/324beca9-b636-4ffb-8b5b-fa527b9ee292?list=studio> to find out!
________________________________

**Pull request merged**
